services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/kyra
      - PORT=5001
      - JWT_SECRET=your_production_secret_key_change_me
      - CLIENT_URL=http://localhost:5001
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
